require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'GomobileIpfs' do

  pod 'Gomobile-IPFS-Bridge', '~> 1.2.0'

  config = use_native_modules! 
  use_react_native!(:path => config["reactNativePath"])
end
